/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Time,
  'sessionId' : IDL.Nat,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Message], []),
  'createSession' : IDL.Func([IDL.Text], [Session], []),
  'deleteSession' : IDL.Func([IDL.Nat], [], []),
  'getMessagesBySession' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'listSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Time,
    'sessionId' : IDL.Nat,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Message], []),
    'createSession' : IDL.Func([IDL.Text], [Session], []),
    'deleteSession' : IDL.Func([IDL.Nat], [], []),
    'getMessagesBySession' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'listSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };